on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: Dockerfile
      env:
        SPLUNK_START_ARGS: --accept-license
        SPLUNK_PASSWORD: password
        SPLUNK_API_HOST: splunk
        SPLUNK_API_PORT: ${{ job.services.splunk.ports[8089] }}
        SPLUNK_API_USERNAME: admin
    steps:
    - uses: actions/checkout@v2
    - run: touch /opt/splunk/etc/splunk-launch.conf
    - run: python3 -m pip install -r bin/requirements-splunk.txt --target=/opt/splunk/lib/python3.7/site-packages
    - run: python3 -m pip install -r requirements.txt
    - run: /opt/splunk/bin/splunk cmd python -m unittest discover
