on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: password
      SPLUNK_API_HOST: splunk
      SPLUNK_API_PORT: 8089
      SPLUNK_API_USERNAME: admin
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t local .
    - name: Run tests
      run: |
        docker run local touch /opt/splunk/etc/splunk-launch.conf && /opt/splunk/bin/splunk cmd python -m unittest discover
