on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: password
      SPLUNK_API_HOST: splunk
      SPLUNK_API_PORT: 8089
      SPLUNK_API_USERNAME: admin
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t local .
    - name: Setup
      run: |
        touch /opt/splunk/etc/splunk-launch.conf
        python3 -m pip install -r bin/requirements-splunk.txt --target=/opt/splunk/lib/python3.7/site-packages
        python3 -m pip install -r requirements.txt
    - name: Run tests
      run: /opt/splunk/bin/splunk cmd python -m unittest discover
