on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build dev
      uses: docker/setup-buildx-action@v1
      if: ${{ !env.ACT }}
  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: amp4e/amp4e_splunk_events_input:latest
      env:
        # PATH: /opt/splunk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        # PYTHONPATH: /opt/splunk/lib/python3.7
        SPLUNK_START_ARGS: --accept-license
        SPLUNK_PASSWORD: Changeme123!
        SPLUNK_API_HOST: splunk
        SPLUNK_API_PORT: ${{ job.services.splunk.ports[8089] }}
        SPLUNK_API_USERNAME: admin
    services:
      splunk:
        image: amp4e/amp4e_splunk_events_input:latest
        ports:
          - 8089:8089
        env:
          SPLUNK_START_ARGS: --accept-license
          SPLUNK_PASSWORD: Changeme123!
    steps:
    - uses: actions/checkout@v2
    - run: touch /opt/splunk/etc/splunk-launch.conf
    - run: python3 -m pip install -r bin/requirements-splunk.txt --target=/opt/splunk/lib/python3.7/site-packages
    - run: python3 -m pip install -r requirements.txt
    - run: /opt/splunk/bin/splunk cmd python -m unittest discover
